console.log("_Ejercicio N° 1_");
console.log("Quitar 1 pila");
console.log("Avanzar 1 paso");
console.log("Quitar 1 pila");
console.log("Avanzar 1 paso");
console.log("Quitar 1 pila");
console.log("Avanzar 1 paso");
console.log("Quitar 1 pila");
console.log("Girar a la izquierda 90°");
console.log("Avanzar 1 paso");
console.log("Quitar 1 pila");
console.log("Avanzar 1 paso");
console.log("Quitar 1 pila");
console.log("Avanzar 1 paso");
console.log("Quitar 1 pila");
console.log("Avanzar 1 paso");
console.log("Quitar 1 pila");
console.log("Avanzar 1 paso");
console.log("Quitar 1 pila");
console.log("¡¡Felicitaciones!!");
